# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('category', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('niño', 'Niño'), ('niña', 'Niña')], max_length=6, verbose_name='categoría')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'ordering': ['-name', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('available', models.PositiveSmallIntegerField(verbose_name='cantidad disponible')),
                ('image', stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('product'), verbose_name='imagen')),
                ('offer', models.PositiveSmallIntegerField(default=0, verbose_name='precio oferta (dejar en 0 si no esta en oferta)')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='precio')),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Color')),
            ],
            options={
                'verbose_name': 'Modelo',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='código')),
                ('description', models.TextField(verbose_name='descripción')),
                ('donations', models.PositiveSmallIntegerField(default=0, verbose_name='donaciones')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('views', models.PositiveSmallIntegerField(default=0, verbose_name='vistas')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Collection')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Kind', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'Producto',
                'ordering': ['-name', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Talla',
            },
        ),
        migrations.AddField(
            model_name='model',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='producto'),
        ),
        migrations.AddField(
            model_name='model',
            name='size',
            field=models.ManyToManyField(related_name='sizes', to='products.Size', verbose_name='talla'),
        ),
        migrations.AlterUniqueTogether(
            name='kind',
            unique_together=set([('category', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('kind', 'name')]),
        ),
    ]
