# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180223_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='size',
            field=models.ManyToManyField(to='products.Size', verbose_name='talla'),
        ),
    ]
