# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_model_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='size',
            field=models.ManyToManyField(related_name='sizes', to='products.Size', verbose_name='talla'),
        ),
    ]
