# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto'},
        ),
    ]
