# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180227_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='available',
            field=models.PositiveSmallIntegerField(verbose_name='cantidad disponible'),
        ),
    ]
