# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171217_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Kind'),
            preserve_default=False,
        ),
    ]
