# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180427_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='offer',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='precio oferta (dejar en 0 si no esta en oferta)'),
        ),
    ]
