# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171219_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='category',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('niño', 'Niño'), ('niña', 'Niña')], max_length=6),
        ),
    ]
