# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20171219_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kind',
            options={'ordering': ['-name', 'category'], 'verbose_name': 'Tipo'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-name', 'kind'], 'verbose_name': 'Producto'},
        ),
        migrations.AlterField(
            model_name='kind',
            name='category',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('niño', 'Niño'), ('niña', 'Niña')], max_length=6, verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='donations',
            field=models.PositiveSmallIntegerField(verbose_name='donaciones'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Kind', verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.PositiveSmallIntegerField(verbose_name='vistas'),
        ),
    ]
