# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20171219_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='donations',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='donaciones'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='vistas'),
        ),
    ]
