# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20171219_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='disponible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='001-p', max_length=10, unique=True, verbose_name='código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='oferta'),
        ),
    ]
