# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stdimage.models
import stdimage.utils
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20171219_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('product'), validators=[stdimage.validators.MinSizeValidator(400, 250), stdimage.validators.MaxSizeValidator(1000, 1000)], verbose_name='imagen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
            },
        ),
    ]
