# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cellphone', models.CharField(blank=True, max_length=50, null=True, verbose_name='celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo')),
                ('first_name', models.CharField(max_length=50, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='apellidos')),
            ],
            options={
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('delivered', models.BooleanField(default=False)),
                ('mount', models.PositiveSmallIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Client', verbose_name='cliente')),
                ('model', models.ManyToManyField(to='products.Model')),
            ],
            options={
                'verbose_name': 'Pedido',
            },
        ),
    ]
